import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { firaSans } from './fonts';
import './globals.css';
import { AppProvider } from '@/utils/context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Si hay para comprar!',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <AppProvider>
        <body className={`${inter.className} ${firaSans.variable}`}>
          {children}
        </body>
      </AppProvider>
    </html>
  );
}
