import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { firaSans } from './fonts';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Si hay para vender!',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inter.className} ${firaSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
